/**
 * dsh facade for the vendored pi-tui fork (`@deepseek-harness-tui/pi-tui`).
 *
 * This module is the ONLY import path production code may use for pi-tui
 * (docs/pi-tui-adoption-refactor-plan.md §1.1/§4). It re-exports exactly the
 * fork public API surface dsh consumes and adds no behavior of its own.
 * Never import `@earendil-works/pi-tui` or fork-private paths directly.
 */
export {
  Box,
  CancellableLoader,
  Container,
  CURSOR_MARKER,
  decodeKittyPrintable,
  Editor,
  HStack,
  Input,
  isFocusable,
  isKeyRelease,
  isKeyRepeat,
  isViewportTUI,
  Key,
  Loader,
  Markdown,
  matchesKey,
  parseKey,
  ProcessTerminal,
  ScrollView,
  SelectList,
  SettingsList,
  Spacer,
  Text,
  TruncatedText,
  TuiAltScreen,
  TuiMainScreen,
  visibleWidth,
  truncateToWidth,
  sliceByColumn,
  stripTerminalSequences,
  wrapTextWithAnsi,
  VStack,
} from '@deepseek-harness-tui/pi-tui'
export type {
  AutocompleteItem,
  AutocompleteProvider,
  AutocompleteSuggestions,
  Component,
  EditorComponent,
  EditorOptions,
  EditorTheme,
  Focusable,
  MarkdownOptions,
  MarkdownTheme,
  OverlayHandle,
  OverlayOptions,
  ScrollViewOptions,
  SelectItem,
  SelectListTheme,
  SettingItem,
  SettingsListTheme,
  SlashCommand,
  StackChild,
  StackEntry,
  StackEntryOptions,
  StackOptions,
  Terminal,
  TUI,
  TuiAltScreenOptions,
  TuiInputListener,
  TuiInputListenerResult,
  TuiMode,
  TuiStopOptions,
  ViewportTUI,
} from '@deepseek-harness-tui/pi-tui'
